# Site settings
title: Zeebo
email: team@zeebo.org
description: > # this means to ignore newlines until "baseurl:"
  Zeebo is a UUV developed by students at California State University, Long Beach.
# Build settings
safe: true
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zeebo.org" # the base hostname & protocol for your site
#twitter_username: mwvartan
#github_username:  vartan
permalink: "/:categories/:year/:month/:day/:title/"
