# Site settings
title: Xeebo
email: michael@mvartan.com
description: > # this means to ignore newlines until "baseurl:"
  Xeebo is UUV developed by California State University, Long Beach students.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xeeboLA.com" # the base hostname & protocol for your site
twitter_username: mwvartan
github_username:  vartan

# Build settings
markdown: kramdown
